
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
   //pseudo random numbers = A set of values or elements that is statistically random
   //                        (Don't use these for any sort of cryptographic security)
   //                        (Use these for games, simulations, etc.)
   //                        (These are not truly random, but they are random enough)
   //                        (They are generated by an algorithm)
   //                        (They are generated by a seed)
   //                        (The seed is a starting point for the algorithm)
   //                        (The seed is usually the current time)
   
 
   // Use current time as a seed for random # generator
   srand(time(0)); //seed the random number generator
   // seed ? = A starting point for the random number generator
   // srand() = Seed the random number generator
   // time(0) = The current time in seconds since 1970
   // srand(time(0)) = Seed the random number generator with the current time in seconds since 1970
   // srand(time(0)) must be called before rand() is called for the first time
   // srand(time(0)) should only be called once in your program
   // srand(time(0)) should not be called repeatedly in a loop
   // srand(time(0)) should not be called repeatedly in a function that is called repeatedly
   // srand(time(0)) should not be called repeatedly in a function that is called repeatedly in a loop
   // srand(time(0)) should not be called repeatedly in a function that is called repeatedly in a function that is called repeatedly in a loop
   
   
 
   // rand() generates a pseudo random # between 0 - 32,767
   // rand() % 6 generates a pseudo random # between 0 - 5
   // rand() % 6 + 1 generates a pseudo random # between 1 - 6 (dice) & +1 Works as offset
   // rand() % 100 generates a pseudo random # between 0 - 99 
   // rand() % 100 + 1 generates a pseudo random # between 1 - 100 (percentages)
   // rand() % n + 1 generates a pseudo random # between 1 - n 
   // rand() % n + m generates a pseudo random # between m - n+m

   int number1 = (rand() % 6) + 1; 
   int number2 = (rand() % 6) + 1;
   int number3 = (rand() % 6) + 1;
 
   printf("%d\n", number1);
   printf("%d\n", number2);
   printf("%d\n", number3);
 
   return 0;
}